# Generated by Django 4.1.3 on 2022-11-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_goals_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="goals",
            name="do_not_use",
            field=models.TextField(blank=True, null=True),
        ),
    ]
