# Generated by Django 4.1.3 on 2022-11-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_goals_do_not_use"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goals",
            name="do_not_use",
            field=models.BooleanField(default=True),
        ),
    ]
